version: '3.9'

services:
  poke_chat:
    platform: linux/amd64
    image: zsy2053/poke_chat
    container_name: poke_chat
    build: .
    ports:
      - "3000:3000"
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - .:/src:cached
    env_file:
      - .env
