# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - style-backend-service

parameters:
  rust: stable
  components: []
  targets: []
  
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            . 
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - script: |
          set -e
          curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal --default-toolchain $RUSTUP_TOOLCHAIN
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        env:
          RUSTUP_TOOLCHAIN: ${{parameters.rust}}
        displayName: "Install rust (*nix)"
        condition: not(eq(variables['Agent.OS'], 'Windows_NT'))

        # Windows.
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y --profile minimal --default-toolchain %RUSTUP_TOOLCHAIN% --default-host x86_64-pc-windows-msvc
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo "##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin"
        env:
          RUSTUP_TOOLCHAIN: ${{parameters.rust}}
        displayName: "Install rust (windows)"
        condition: eq(variables['Agent.OS'], 'Windows_NT')

      # Set correct toolchain
      - bash: |
          rustup default $RUSTUP_TOOLCHAIN
          rustup update $RUSTUP_TOOLCHAIN
        env:
          RUSTUP_TOOLCHAIN: ${{parameters.rust}}
        displayName: "Set correct Rust version"

      # Install additional targets:
      - ${{ each target in parameters.targets }}:
        - script: rustup target add ${{ target }}
          displayName: "Adding target '${{ target }}'"

      # Install additional components:
      - ${{ each component in parameters.components }}:
        - script: rustup component add ${{ component }}
          displayName: "Adding component '${{ component }}'"

      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'style-backend-service'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_38DD28B05E2E438E95B8F0938E906B87 }}
